server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #使用服务名称作为路由地址
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
            - After=2022-07-12T13:02:09.871+08:00[Asia/Shanghai]  # 断言 路由在配置时间后生效
            - Cookie=username,zzyy  # Cookie=cookieName,正则表达式
                                    # 测试方法 curl http://localhost:9527/payment/lb --cookie "username=zzyy"
                                    # 乱发问题 https://blog.csdn.net/leedee/article/details/82685636
            - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
                                        # 测试 curl http://localhost:9527/payment/lb --cookie "username=zzyy" -H "X-Request-Id:11"
            - Host=**.surge.com  # curl http://localhost:9527/payment/lb -H "Host:afae.surge.com"


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka